"use client";
import {useState,useRef,useEffect,useCallback} from 'react';
import {ArrowUpRight,ArrowRight,Fingerprint,Scale,ShieldCheck,Layers3,Play,ScanLine,LoaderCircle,ExternalLink,Square,Check,MessagesSquare} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {analysts,labels,parseTickers,type Event,type AnalystId,type Research,type Ballot,type Report,type View} from '@/lib/council-types';
const icons={quality:Fingerprint,value:Scale,risk:ShieldCheck};
const money=(n:number|null)=>n===null?'Not verified':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
function SafeText({text}:{text:string}){return <div className="prose-report">{text.split('\n').filter(Boolean).map((line,i)=><p key={i}>{line.replace(/^#{1,4}\s+/,'').split(/(\[[^\]]+\]\(https?:\/\/[^\s)]+\))/g).map((part,j)=>{const match=part.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);return match?<a key={j} href={match[2]} target="_blank" rel="noopener noreferrer">{match[1]}</a>:part.replace(/\*\*/g,'');})}</p>)}</div>}
export default function Home(){
 const [tickers,setTickers]=useState('MSFT, GOOGL, V, BRK.B, JNJ');
 const [mode,setMode]=useState('discover');const [tab,setTab]=useState('shortlist');
 const [research,setResearch]=useState<Research[]>([]);const [ballots,setBallots]=useState<Ballot[]>([]);const [report,setReport]=useState<Report|null>(null);const [selected,setSelected]=useState('');
 const [running,setRunning]=useState(false);const [status,setStatus]=useState('Awaiting first session');const [error,setError]=useState('');const [active,setActive]=useState<AnalystId>();const [universe,setUniverse]=useState<string[]>([]);const [ready,setReady]=useState<boolean|null>(null);const [signedIn,setSignedIn]=useState(true);
 const abort=useRef<AbortController|null>(null);const busy=useRef(false);
 useEffect(()=>{fetch('/api/health').then(r=>r.json() as Promise<{ready:boolean;signedIn:boolean}>).then(d=>{setReady(d.ready);setSignedIn(d.signedIn);}).catch(()=>setReady(false));return ()=>abort.current?.abort();},[]);
 const start=useCallback(async(override?:string)=>{
  if(busy.current)throw new Error('A council session is already running.');
  const chosenMode=override?'compare':mode;const symbols=override||tickers;
  try{if(chosenMode==='compare')parseTickers(symbols);}catch(e){setError((e as Error).message);return;}
  busy.current=true;setRunning(true);setError('');setReport(null);setResearch([]);setBallots([]);setUniverse([]);setTab('room');setStatus('Opening the research session…');
  const control=new AbortController();abort.current=control;let complete=false;
  try{
   const response=await fetch('/api/council',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:chosenMode,tickers:symbols}),signal:control.signal});
   if(!response.ok){const d=await response.json() as {error?:string};throw new Error(d.error||'Unable to start the council.');}
   if(!response.body)throw new Error('The research stream is unavailable.');
   const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';
   const consume=(line:string)=>{if(!line.trim())return;const e=JSON.parse(line) as Event;
    if(e.type==='status'){setStatus(e.message);setActive(e.analyst);}
    if(e.type==='universe')setUniverse(e.tickers);
    if(e.type==='research')setResearch(old=>[...old.filter(r=>r.analyst!==e.data.analyst),e.data]);
    if(e.type==='ballot')setBallots(old=>[...old,e.data]);
    if(e.type==='error')throw new Error(e.message);
    if(e.type==='complete'){complete=true;setReport(e.data);setSelected(e.data.decisions[0]?.ticker||'');setStatus('Session complete');setTab('shortlist');}
   };
   while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let n;while((n=buffer.indexOf('\n'))>=0){consume(buffer.slice(0,n));buffer=buffer.slice(n+1);}}
   buffer+=decoder.decode();consume(buffer);if(!complete)throw new Error('The session ended before the council reached a final result.');
  }catch(e){if(control.signal.aborted){setStatus('Session stopped');setError('The session was stopped. Partial research is not a final assessment.');}else{setStatus('Session incomplete');setError(e instanceof Error?e.message:'The research session failed.');}control.abort();}
  finally{setRunning(false);setActive(undefined);busy.current=false;}
 },[mode,tickers]);
 useEffect(()=>{
  type Registry={registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown};const registry=(document as Document & {modelContext?:Registry}).modelContext;if(!registry)return;const lifecycle=new AbortController();
  const tools=[{name:'stage_stock_comparison',description:'Set 1–8 US stock symbols in the visible comparison form. Does not start paid research.',inputSchema:{type:'object',properties:{symbols:{type:'string'}},required:['symbols'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(busy.current)throw new Error('Wait for the current session.');const symbols=(input as {symbols?:unknown})?.symbols;if(typeof symbols!=='string')throw new Error('symbols must be a string');const values=parseTickers(symbols);setTickers(values.join(', '));setMode('compare');return {symbols:values,staged:true};}},{name:'read_council_result',description:'Read the completed council result shown on this page, or its current status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({status,report})}];
  for(const t of tools)try{Promise.resolve(registry.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();
 },[status,report]);
 const decision=report?.decisions.find(d=>d.ticker===selected);const valueView=decision?.views.find(v=>v.analyst==='value');
 const allSources=[...new Map(research.flatMap(r=>r.sources).map(s=>[s.url,s])).values()];
 return <div className="app-shell"><header className="masthead"><a href="/" className="brand"><Layers3 size={26}/> council<span className="brand-divider"/><span className="brand-sub">INVESTMENT RESEARCH</span></a><span className="private-label">Private workspace</span></header><main>
  <div className="title-row"><div><div className="eyebrow">THREE MINDS. ONE INVESTMENT THESIS.</div><h1>Your investment council<span>.</span></h1><p className="intro">Independent research. Open debate. A more considered shortlist.</p></div><div className="mandate"><span>YOUR MANDATE</span><strong>3–5 years <i/> Moderate risk</strong><small>US-listed stocks · Long-term investing</small></div></div>
  <section className="analyst-grid" aria-label="Your three analysts">{analysts.map((a,i)=>{const Icon=icons[a.id];const done=ballots.some(b=>b.analyst===a.id);return <article className={`analyst ${a.color} ${active===a.id?'is-active':''}`} key={a.id}><div className="analyst-top"><Icon size={28}/><span>0{i+1}</span></div><div className="eyebrow">{a.specialty}</div><h2>{a.name}</h2><p>{a.detail}</p><div className="analyst-state">{done?'Verdicts submitted':running?(research.some(r=>r.analyst===a.id)?'Reviewing the council':'Researching sources'):'Ready to research'}{done?<Check size={15}/>:running?<LoaderCircle className="spin" size={15}/>:<ArrowUpRight size={15}/>}</div></article>})}</section>
  <section className="research-bar"><div><label htmlFor="tickers">Bring stocks to the table</label><Tabs value={mode} onValueChange={v=>!running&&setMode(v)}><TabsList className="mode-switch"><TabsTrigger value="discover" disabled={running}>Discover candidates</TabsTrigger><TabsTrigger value="compare" disabled={running}>Compare symbols</TabsTrigger></TabsList></Tabs></div><form onSubmit={e=>{e.preventDefault();void start();}}>{mode==='compare'?<Input id="tickers" value={tickers} disabled={running} onChange={e=>setTickers(e.target.value)} aria-label="Stock symbols" placeholder="MSFT, V, BRK.B"/>:<p className="discovery-scope">A focused search across US sectors.<br/><span>5–6 candidates · Not an exhaustive market screen</span></p>}{running?<Button type="button" variant="outline" className="stop-button" onClick={()=>abort.current?.abort()}><Square size={14}/> Stop session</Button>:<Button className="run-button" disabled={ready===false}><Play size={15}/> Convene council</Button>}</form></section>
  {ready===false&&<div className="error-banner" role="alert">{!signedIn?<><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in to your private workspace</a> to start a council session.</>:<>The AI connection is not configured. Reconnect the API account before starting.</>}</div>}
  {error&&<div className="error-banner" role="alert">{error}{error.includes("credits")&&<> <a href="https://platform.openai.com/settings/organization/billing" target="_blank" rel="noopener noreferrer">Open API billing</a>.</>}</div>}
  {(running||report)&&<div className="session-strip" aria-live="polite">{running?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}<span>{status}</span>{universe.length>0&&<small>{universe.join(' · ')}</small>}</div>}
  <section className="workspace-grid"><div className="panel results-panel"><Tabs value={tab} onValueChange={setTab}><div className="panel-heading"><TabsList variant="line"><TabsTrigger value="shortlist">Shortlist {report?`(${report.decisions.length})`:''}</TabsTrigger><TabsTrigger value="room">Council room</TabsTrigger><TabsTrigger value="sources">Sources {allSources.length?`(${allSources.length})`:''}</TabsTrigger></TabsList>{report&&<span>{new Date(report.createdAt).toLocaleDateString()}</span>}</div>
  <TabsContent value="shortlist">{!report?<div className="empty-state"><ScanLine size={35}/><h3>Conviction starts with evidence.</h3><p>{running?'Your analysts are researching and debating. Follow their progress in the council room.':'Convene the council to compare businesses, debate their prices, and surface the risks before making a call.'}</p><div className="process"><span>Research</span><ArrowRight size={16}/><span>Challenge</span><ArrowRight size={16}/><span>Decide</span></div></div>:<><Table><TableHeader><TableRow><TableHead>Company</TableHead><TableHead>Council view</TableHead><TableHead>Support</TableHead></TableRow></TableHeader><TableBody>{report.decisions.map(d=><TableRow key={d.ticker} data-state={d.ticker===selected?'selected':undefined}><TableCell><button className="stock-button" onClick={()=>setSelected(d.ticker)} aria-pressed={selected===d.ticker}><strong>{d.ticker}</strong><span>{d.company}</span></button></TableCell><TableCell><span className={`verdict ${d.verdict}`}>{labels[d.verdict]}</span></TableCell><TableCell><div className="votes" aria-label={`${d.support} of 3 analysts support further research`}>{[0,1,2].map(n=><i key={n} className={n<d.support?'filled':''}/>)}<span>{d.support}/3</span></div></TableCell></TableRow>)}</TableBody></Table>
  {decision&&<div className="decision"><div className="decision-title"><div><div className="eyebrow">THE INVESTMENT CASE</div><h2>{decision.ticker} <span>{decision.company}</span></h2></div><span className={`verdict ${decision.verdict}`}>{labels[decision.verdict]}</span></div><p className="decision-reason">{decision.reason}</p><div className="valuation-grid"><div><span>Researched price · USD</span><strong>{money(valueView?.quote??null)}</strong><small>{valueView?.quoteDate?`As of ${valueView.quoteDate} · Not a live quote`:'A dated quote could not be verified'}</small></div><div><span>Estimated fair value · USD</span><strong>{valueView?.fairLow!=null&&valueView?.fairHigh!=null?`${money(valueView.fairLow)} – ${money(valueView.fairHigh)}`:'Not established'}</strong><small>Scenario estimate, not a price forecast</small></div></div>{valueView&&<p className="assumptions">{valueView.valuationAssumptions}</p>}<div className="view-list">{decision.views.map(v=><ViewCard key={v.analyst} view={v}/>)}</div></div>}</>}</TabsContent>
  <TabsContent value="room"><div className="room-content">{research.length===0?<div className="empty-state">{running?<LoaderCircle size={32} className="spin"/>:<MessagesSquare size={32}/>}<h3>{running?'The council is gathering evidence.':'A conversation you can inspect.'}</h3><p>{running?'Each analyst is forming an independent view. Their reports will appear here as they finish.':'First, independent research. Then each analyst challenges a peer and responds to an objection. You see what changed and what remains unresolved.'}</p></div>:<><div className="round-label">01 / INDEPENDENT RESEARCH</div>{research.map(r=><article className="research-entry" key={r.analyst}><h3>{analysts.find(a=>a.id===r.analyst)?.name}</h3><SafeText text={r.text}/></article>)}{ballots.length>0&&<div className="round-label">02 / CHALLENGE & REVISED VIEWS</div>}{ballots.map(b=><article className="debate-entry" key={b.analyst}><h3>{analysts.find(a=>a.id===b.analyst)?.name}</h3><h4>Challenge to the council</h4><p>{b.challenge}</p><h4>Response to peer concerns</h4><p>{b.response}</p><div className="ballot-tags">{b.views.map(v=><span key={v.ticker}>{v.ticker} <em className={`verdict ${v.verdict}`}>{labels[v.verdict]}</em></span>)}</div></article>)}</>}</div></TabsContent>
  <TabsContent value="sources">{allSources.length===0?<div className="empty-state"><ExternalLink size={32}/><h3>Trace every claim.</h3><p>Source links retrieved during research appear here. Sources may contain older reporting; the analysts must identify dates and gaps.</p></div>:<div className="source-list">{allSources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer"><span>{String(i+1).padStart(2,'0')}</span><div><strong>{s.title}</strong><small>{new URL(s.url).hostname}</small></div><ExternalLink size={15}/></a>)}</div>}</TabsContent></Tabs></div>
  <aside className="panel principles"><div className="eyebrow">THE COUNCIL’S STANDARD</div><h2>A good company.<br/>At a sensible price.</h2><p>Every candidate must survive all three perspectives.</p><ul><li><span>01</span> Evidence before conviction</li><li><span>02</span> Downside before upside</li><li><span>03</span> Disagreement stays visible</li></ul><div className="standards"><h3>How a stock makes the shortlist</h3><p>Three supportive views, cited evidence, a price dated within seven days, and no material risk objection.</p><h3>Agreement ≠ certainty</h3><p>These are three roles using the same AI model. Shared errors are possible. Review the original sources.</p></div><div className="note">Research for your review. No trades are placed. Each session uses your API account and may incur charges. Results remain on this page until you refresh or start a new session.</div></aside></section><footer>COUNCIL <span>Built for patience. Grounded in sources.</span></footer></main></div>
}
function ViewCard({view}:{view:View&{analyst:AnalystId}}){const a=analysts.find(a=>a.id===view.analyst)!;return <article className={`view-card ${a.color}`}><div><h3>{a.name}</h3><span className={`verdict ${view.verdict}`}>{labels[view.verdict]}</span></div><p>{view.thesis}</p><h4>What could go wrong</h4><p>{view.concern}</p><h4>What would change this view</h4><p>{view.changeMind}</p><div className="evidence-links">{view.evidenceUrls.map((u,i)=><a href={u} target="_blank" rel="noopener noreferrer" key={u}>Source {i+1} <ExternalLink size={12}/></a>)}</div></article>}
